name: provider_start
description: A production ready flutter application template for the provider architecture.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0

environment:
  sdk: ">=3.0.0"

scripts:
  build: flutter packages pub run build_runner build --delete-conflicting-outputs
  watch: flutter packages pub run build_runner watch --delete-conflicting-outputs
  test: flutter test
  analyze: flutter analyze --no-pub
  format: flutter format lib/**

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  stacked: 3.4.0

  # Utilities
  shared_preferences: 2.1.2
  connectivity: 3.0.6
  app_settings: 4.2.0
  device_info: 2.0.3
  path_provider: 2.0.15
  hive: 2.2.3
  hive_flutter: 1.1.0
  built_value: 8.6.1
  pedantic: 1.11.1
  logging: 1.2.0
  get_it: 7.6.0
  mime: 1.0.4
  get: 4.6.5
  dio: 5.2.0+1

  # UI Utilities
  flutter_platform_widgets: 3.3.5

  # UI Widgets
  cupertino_icons: 1.0.5
  flare_flutter: 3.0.2
  auto_route: 7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.13.1
  built_value_generator: 8.6.1
  hive_generator: 2.0.0
  auto_route_generator: 7.1.1
  build_runner: 2.4.5
  mockito: 5.4.1
  logger: 1.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/fonts/
    - assets/images/
    - assets/lang/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
